Repository leahcimto/leahcimto.github.io, pull requests merged in 2020-12, with the labels that each got.

#1 Create LICENSE
  LICENSE
Labels: High Priority, URGENT

#12 Add a Top Navigation Bar
  index.html
Labels: pending review

#24 Dark theme and minor improvements
  404.html
  fiveyears.html
  index.html
  javascript.js
  shop.html
  stylesheet.css
  wat.html
Labels: enhancement, unreviewed
